# Generated by Django 3.2a1 on 2021-03-28 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='nickname',
            field=models.CharField(help_text='Enter Nickname', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter a Make', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Enter at least two character')]),
        ),
    ]
